### ISSUE TITLE
Rearrange sponsor section

### ISSUE THREAD

**Issue by maxellmilay** [maxellmilay/otakufest-ph#12]
- from left to right, major sponsors, minor sponsors, then the others

**Comment by Loweso** [comment]
@maxellmilay @arwin50 already done

![image](https://github.com/maxellmilay/otakufest-ph/assets/119489421/ca00a531-042f-45a5-b0b2-dd8de4a66b36)
![image](https://github.com/maxellmilay/otakufest-ph/assets/119489421/fad40db8-5a15-4c30-b173-dfa4b2ff1947)

code prbbly not clean (see:)

![image](https://github.com/maxellmilay/otakufest-ph/assets/119489421/0da4c20e-7a4c-46b9-a40c-d2b99217f381)
sponsors not mapped because of difference in aspect ratio
